site_name: PG-Strom Manual
site_description: PG-Strom v2.0 Official Documentation
site_author: PG-Strom Development Team
theme:
    name: readthedocs
@en{
    custom_dir: docs/custom_en
}
@ja{
    custom_dir: docs/custom_ja
}
pages:
@en{
- 'Home' : 'index.md'
- 'Install' : 'install.md'
- 'Tutorial' : 'tutorial.md'
- 'Advanced Features' : 'features.md'
- 'PL/CUDA' : 'plcuda.md'
- 'References' : 'references.md'
- 'Release Note' : 'release_note.md'
}
@ja{
- 'はじめに' : 'index.md'
- 'インストール' : 'install.md'
- '利用ガイド' : 'tutorial.md'
- '先進機能' : 'features.md'
- 'PL/CUDA' : 'plcuda.md'
- 'リファレンス' : 'references.md'
- 'リリースノート' : 'release_note.md'
}
extra_css:
    - "//fonts.googleapis.com/earlyaccess/notosansjp.css"
    - "//fonts.googleapis.com/css?family=Open+Sans:600,800"
    - "custom.css"
markdown_extensions:
    - admonition
    - footnotes
    - def_list
